name: SQL-Linter
on: [ push ]
#jobs:
#    linter:
#        name: flake8-sql
#        runs-on: ubuntu-latest
#        steps:
#            -   name: Git clone our repo
#                uses: actions/checkout@v3
#
#            -   name: Установка Python
#                uses: actions/setup-python@v4
#                with:
#                    python-version: 3.9.0
#            -   name: Установка зависимостей
#                run: |
#                    python -m pip install --upgrade pip
#                    pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 flake8-bandit==2.1.2 bandit==1.7.2
#            -   name: Flake8
#                run: flake8 .
jobs:
    changedfiles:
        runs-on: ubuntu-latest
        # Map a step output to a job output
        outputs:
            all: ${{ steps.changes.outputs.all}}
            ts: ${{ steps.changes.outputs.ts }}
        steps:
            # Make sure we have some code to diff.
            -   name: Checkout repository
                uses: actions/checkout@v2
            -   name: Get changed files
                id: changes
                # Set outputs using the command.
                run: |
                    echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
                    echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"
    lint:
        runs-on: ubuntu-latest
        # require the first job to have ran
        needs: changedfiles
        # only run there are changed files
        if: ${{needs.changedfiles.outputs.ts}}
        steps:
            -   name: echo changed files
                run: echo ${{needs.changedfiles.outputs.ts}}

            -   name: Install Python
                uses: actions/setup-python@v4

            -   name: Установка зависимостей
                run: |
                    python -m pip install --upgrade pip
                    pip install flake8 flake8-sql

            -   name: Flake8
                run: flake8 .